name: p3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - backports.weakref=1.0rc1=py35_0
  - bleach=1.5.0=py35_0
  - distributed=1.20.2=py35_0
  - html5lib=0.9999999=py35_0
  - jupyter_contrib_core=0.3.3=py35_1
  - jupyter_nbextensions_configurator=0.3.0=py35_0
  - markdown=2.6.9=py35_0
  - asn1crypto=0.23.0=py35h4ab26a5_0
  - backports=1.0=py35hd471ac7_1
  - bcolz=1.1.2=py35hcb27967_0
  - binutils_impl_linux-64=2.28.1=h04c84fa_2
  - binutils_linux-64=7.2.0=25
  - bokeh=0.12.13=py35h2f9c1c0_0
  - boto=2.48.0=py35h2cfd601_1
  - bz2file=0.98=py35_0
  - bzip2=1.0.6=h6d464ef_2
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2017.11.5=py35h9749603_0
  - cffi=1.11.2=py35hc7b2db7_0
  - chardet=3.0.4=py35hb6e9ddf_1
  - click=6.7=py35h353a69f_0
  - cloudpickle=0.5.2=py35hbe86bc5_0
  - cryptography=2.1.4=py35hbeb2da1_0
  - cudatoolkit=8.0=3
  - cudnn=6.0.21=cuda8.0_0
  - cycler=0.10.0=py35hc4d5149_0
  - cython=0.27.3=py35h6cdc64b_0
  - dask=0.16.0=py35hcb8ecc8_0
  - dask-core=0.16.0=py35hfc66869_0
  - dbus=1.10.22=h3b5a359_0
  - decorator=4.1.2=py35h3a268aa_0
  - entrypoints=0.2.3=py35h48174a2_2
  - expat=2.2.5=he0dffb1_0
  - fastcache=1.0.2=py35hec2bbaa_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - gcc_impl_linux-64=7.2.0=hc5ce805_2
  - gcc_linux-64=7.2.0=25
  - gensim=3.1.0=py35h7300b16_0
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py35hd0a1c9a_2
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - gxx_impl_linux-64=7.2.0=hd3faf3d_2
  - gxx_linux-64=7.2.0=25
  - h5py=2.7.1=py35h8d53cdc_0
  - hdf5=1.10.1=h9caa474_1
  - heapdict=1.0.0=py35h51e6c10_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py35h8605a33_1
  - imageio=2.2.0=py35hd0a6de2_0
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipykernel=4.7.0=py35h2f9c1c0_0
  - ipython=6.2.1=py35hd850d2a_1
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.0.5=py35h8147dc1_0
  - jedi=0.11.0=py35_2
  - jinja2=2.10=py35h480ab6d_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35hd38625c_0
  - jupyter_client=5.1.0=py35h2bff583_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.4.0=py35ha89e94b_0
  - keras=2.1.2=py35_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libgpuarray=0.7.5=h14c3975_0
  - libpng=1.6.32=hbd3595f_4
  - libprotobuf=3.4.1=h5b8497f_0
  - libsodium=1.0.15=hf101ebd_0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.4=h2e8b1d7_6
  - locket=0.2.0=py35h170bc82_1
  - lzo=2.10=h49e0be7_2
  - mako=1.0.7=py35h69899ea_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.1.1=py35ha26af80_0
  - mistune=0.8.1=py35h9251d8c_0
  - mkl=2018.0.1=h19d6760_4
  - mkl-service=1.1.2=py35h0fc7090_4
  - mpc=1.0.3=hec55b23_5
  - mpfr=3.1.5=h11a74b3_2
  - mpmath=1.0.0=py35h7ce6e34_2
  - msgpack-python=0.4.8=py35h783f4c8_0
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - ncurses=6.0=h9df7e31_2
  - networkx=2.0=py35hc690e10_0
  - nltk=3.2.5=py35h09ad193_0
  - notebook=5.2.2=py35he644770_0
  - numexpr=2.6.4=py35h119f745_0
  - numpy=1.13.3=py35hd829ed6_0
  - olefile=0.44=py35h2c86149_0
  - openssl=1.0.2n=hb7f436b_0
  - pandas=0.22.0=py35hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py35h1565a15_1
  - parso=0.1.1=py35h1b200a3_0
  - partd=0.3.8=py35h68187f2_0
  - pcre=8.41=hc27e229_1
  - pexpect=4.3.0=py35hf410859_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=5.0.0=py35h3deb7b8_0
  - pip=9.0.1=py35h7e7da9d_4
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - protobuf=3.4.1=py35he6b9134_0
  - psutil=5.4.1=py35h2e39a06_0
  - ptyprocess=0.5.2=py35h38ce0a3_0
  - pycparser=2.18=py35h61b3040_1
  - pygments=2.2.0=py35h0f41973_0
  - pygpu=0.7.5=py35h14c3975_0
  - pyopenssl=17.5.0=py35h4f8b8c8_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.6.0=py35h0e41ada_5
  - pysocks=1.6.7=py35h6aefbb0_1
  - pytables=3.4.2=py35hfa98db7_2
  - python=3.5.4=h417fded_24
  - python-dateutil=2.6.1=py35h90d5b31_1
  - pytz=2017.3=py35hb13c558_0
  - pywavelets=0.5.2=py35h53ec731_0
  - pyyaml=3.12=py35h46ef4ae_1
  - pyzmq=16.0.3=py35ha889422_0
  - qt=5.6.2=h974d657_12
  - qtconsole=4.3.1=py35h4626a06_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py35hb9e6ad1_1
  - scikit-image=0.13.1=py35h14c3975_1
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=1.0.0=py35hcbbe4a2_0
  - setuptools=36.5.0=py35ha8c1747_0
  - simplegeneric=0.8.1=py35h2ec4104_0
  - sip=4.18.1=py35h9eaea60_2
  - six=1.11.0=py35h423b573_1
  - smart_open=1.5.3=py35_0
  - sortedcontainers=1.5.7=py35h683703c_0
  - sqlite=3.20.1=hb898158_2
  - sympy=1.1.1=py35h919b29a_0
  - tblib=1.3.2=py35hf1eb0b4_0
  - tensorflow=1.3.0=0
  - tensorflow-base=1.3.0=py35h79a3156_1
  - tensorflow-gpu=1.3.0=0
  - tensorflow-gpu-base=1.3.0=py35cuda8.0cudnn6.0_1
  - tensorflow-tensorboard=0.1.5=py35_0
  - terminado=0.6=py35hce234ed_0
  - testpath=0.3.1=py35had42eaf_0
  - theano=1.0.1=py35h6bb024c_0
  - tk=8.6.7=hc745277_3
  - toolz=0.8.2=py35h90f1797_0
  - tornado=4.5.2=py35hf879e1d_0
  - tqdm=4.19.4=py35h68e51d2_0
  - traitlets=4.3.2=py35ha522a97_0
  - ujson=1.35=py35_0
  - urllib3=1.22=py35h2ab6e29_0
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - werkzeug=0.12.2=py35hbfc1ea6_0
  - wheel=0.30.0=py35hd3883cf_1
  - widgetsnbextension=3.0.8=py35h84cb72a_0
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.2=hbedb6e5_2
  - zict=0.1.3=py35h29275ca_0
  - zlib=1.2.11=ha838bed_2
  - pytorch=0.3.0=py35_cuda8.0.61_cudnn7.0.3hb362f6e_4
  - torchvision=0.2.0=py35heaa392f_1
  - pip:
    - keras-tqdm==2.0.1
    - tables==3.4.2
    - torch==0.3.0.post4
    - xgboost==0.7.post3
prefix: /home/roebius/anaconda/envs/p3

